select * from member;

CREATE TABLE MEMBER (
  MEMBER_NO NUMBER(5) NOT NULL,
  MEMBER_ID VARCHAR2(20) NOT NULL,
  MEMBER_PW VARCHAR2(300) NOT NULL,
  MEMBER_NAME VARCHAR2(20) NOT NULL,
  MEMBER_NICKNAME VARCHAR2(20) NOT NULL,
  MEMBER_EMAIL VARCHAR2(30) NOT NULL,
  MEMBER_ADDR VARCHAR2(300) NOT NULL,
  MEMBER_TEL VARCHAR2(30) NOT NULL,
  MEMBER_REGDATE DATE DEFAULT SYSDATE,
  MEMBER_MODDATE DATE DEFAULT SYSDATE,
  MEMBER_STATUS NUMBER(1) DEFAULT 1,
  MEMBER_SNS_ACCOUNT VARCHAR2(10) DEFAULT 'N/A',
  MEMBER_PROFILE VARCHAR2(300)
);
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_PK PRIMARY KEY (MEMBER_NO);
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_ID_UNI UNIQUE (MEMBER_ID);
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_NICK_UNI UNIQUE (MEMBER_NICKNAME);
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_SNS_ACCOUNT_CHK CHECK(MEMBER_SNS_ACCOUNT IN ('N/A', 'G','F'));
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_STATUS_CHK CHECK(MEMBER_STATUS IN (0,1));

CREATE SEQUENCE MEMBER_SEQ START WITH 1;
CREATE OR REPLACE TRIGGER MEMBER_TRG
BEFORE INSERT ON MEMBER
FOR EACH ROW
BEGIN
SELECT MEMBER_SEQ.NEXTVAL
INTO :NEW.MEMBER_NO
FROM DUAL;
END;
/
COMMIT;

CREATE TABLE HASHTAG (
  HASHTAG_NO NUMBER(3) NOT NULL,
  HASHTAG_NAME VARCHAR2(50) NOT NULL,
  HASHTAG_COUNT NUMBER(5) DEFAULT 1
);
ALTER TABLE HASHTAG ADD CONSTRAINT HASHTAG_PK PRIMARY KEY(HASHTAG_NO);
CREATE SEQUENCE HAHSTAG_SEQ START WITH 1;
CREATE OR REPLACE TRIGGER HAHSTAG_TRG
BEFORE INSERT ON HASHTAG
FOR EACH ROW
BEGIN
SELECT HASHTAG_SEQ.NEXTVAL
INTO :NEW.TAG_NO
FROM DUAL;
END;
/
COMMIT;
CREATE TABLE BOARD_FREE(
 BOARD_NO NUMBER(5) NOT NULL,
 BOARD_WRITER VARCHAR2(20) NOT NULL,
 BOARD_TITLE VARCHAR2(50) NOT NULL,
 BOARD_CONTENT VARCHAR2(3000) NOT NULL,
 BOARD_DATE DATE DEFAULT SYSDATE,
 BOARD_COUNT NUMBER(5) DEFAULT 0
)
ALTER TABLE BOARD_FREE ADD CONSTRAINT BOARD_FREE_PK PRIMARY KEY(BOARD_NO);
ALTER TABLE BOARD_FREE ADD CONSTRAINT BOARD_FREE_FK FOREIGN KEY(BOARD_WRITER) REFERENCES MEMBER(MEMBER_NICKNAME);
CREATE SEQUENCE BOARD_FREE_SEQ START WITH 1;
CREATE OR REPLACE TRIGGER BOARD_FREE_TRG
BEFORE INSERT ON BOARD_FREE
FOR EACH ROW
BEGIN
SELECT BOARD_FREE_SEQ.NEXTVAL
INTO :NEW.BOARD_NO
FROM DUAL;
END;
/
COMMIT;
CREATE TABLE FILE_BOARD_FREE(
 FILE_BOARD_NO NUMBER(3) NOT NULL,
 FILE_ORG_NAME VARCHAR2(300) NOT NULL,
 FILE_RE_NAME VARCHAR2(300) NOT NULL
)
ALTER TABLE FILE_BOARD_FREE ADD CONSTRAINT FILE_BOARD_FREE_FK FOREIGN KEY(FILE_BOARD_NO) REFERENCES BOARD_FREE(BOARD_NO);
CREATE TABLE HASHTAG_FREE(
 HASHTAG_BOARD_NO NUMBER(3) NOT NULL,
 HASHTAG_NO NUMBER(3) NOT NULL
);
ALTER TABLE HASHTAG_FREE ADD CONSTRAINT HASHTAG_FREE_BNO_FK FOREIGN KEY(HASHTAG_BOARD_NO) REFERENCES BOARD_FREE(BOARD_NO);
ALTER TABLE HASHTAG_FREE ADD CONSTRAINT HASHTAG_FREE_NO_FK FOREIGN KEY(HASHTAG_NO) REFERENCES HASHTAG(HASHTAG_NO);
CREATE TABLE QNA_CATEGORY(
 CATEGORY_NO NUMBER(3) NOT NULL,
 CATEGORY_NAME VARCHAR2(200) NOT NULL
)
CREATE SEQUENCE QNA_CATEGORY_SEQ START WITH 1;
CREATE OR REPLACE TRIGGER QNA_CATEGORY
BEFORE INSERT ON CATEGORY_NO
FOR EACH ROW
BEGIN
SELECT QNA_CATEGORY_SEQ.NEXTVAL
INTO :NEW.CATEGORY_NO
FROM DUAL;
END;
/
COMMIT;
CREATE TABLE BOARD_QNA(
 BOARD_NO NUMBER(5) NOT NULL,
 BOARD_WRITER VARCHAR2(20) NOT NULL,
 BOARD_TITLE VARCHAR2(50) NOT NULL,
 BOARD_CONTENT VARCHAR2(3000) NOT NULL,
 BOARD_DATE DATE DEFAULT SYSDATE,
 BOARD_COUNT NUMBER(5) DEFAULT 0,
 BOARD_CATEGORY NUMBER(20) NOT NULL
)
ALTER TABLE BOARD_QNA ADD CONSTRAINT BOARD_QNA_PK PRIMARY KEY(BOARD_NO);
ALTER TABLE BOARD_QNA ADD CONSTRAINT BOARD_QNA_FK FOREIGN KEY(BOARD_WRITER) REFERENCES MEMBER(MEMBER_NICKNAME);
ALTER TABLE BOARD_QNA ADD CONSTRAINT BOARD_QNA_CATE_FK FOREIGN KEY(BOARD_CATEGORY) REFERENCES QNA_CATEGORY(CATEGORY_NO);
CREATE SEQUENCE BOARD_QNA_SEQ START WITH 1;
CREATE OR REPLACE TRIGGER BOARD_QNA_TRG
BEFORE INSERT ON BOARD_QNA
FOR EACH ROW
BEGIN
SELECT BOARD_QNA_SEQ.NEXTVAL
INTO :NEW.BOARD_NO
FROM DUAL;
END;
/
COMMIT;
CREATE TABLE HASHTAG_QNA(
 HASHTAG_BOARD_NO NUMBER(3) NOT NULL,
 HASHTAG_NO NUMBER(3) NOT NULL
);
ALTER TABLE HASHTAG_QNA ADD CONSTRAINT HASHTAG_QNA_BNO_FK FOREIGN KEY(HASHTAG_BOARD_NO) REFERENCES BOARD_QNA(BOARD_NO);
ALTER TABLE HASHTAG_QNA ADD CONSTRAINT HASHTAG_QNA_NO_FK FOREIGN KEY(HASHTAG_NO) REFERENCES HASHTAG(HASHTAG_NO);
ALTER TABLE HASHTAG_QNA ADD CONSTRAINT HASHTAG_PK PRIMARY KEY(HASHTAG_NO);
CREATE TABLE FILE_BOARD_QNA(
 FILE_BOARD_NO NUMBER(3) NOT NULL,
 FILE_ORG_NAME VARCHAR2(300) NOT NULL,
 FILE_RE_NAME VARCHAR2(300) NOT NULL
)
ALTER TABLE FILE_BOARD_QNA ADD CONSTRAINT FILE_BOARD_QNA_FK FOREIGN KEY(FILE_BOARD_NO) REFERENCES BOARD_QNA(BOARD_NO);
