CREATE TABLE BOARD_JOB(
 BOARD_NO NUMBER(5) NOT NULL,
 BOARD_WRITER VARCHAR2(20) NOT NULL,
 BOARD_TITLE VARCHAR2(50) NOT NULL,
 BOARD_CONTENT VARCHAR2(3000) NOT NULL,
 BOARD_DATE DATE DEFAULT SYSDATE,
 BOARD_COUNT NUMBER(5) DEFAULT 0,
 BOARD_STATUS NUMBER(1) DEFAULT 1
)
ALTER TABLE BOARD_JOB ADD CONSTRAINT BOARD_JOB_PK PRIMARY KEY(BOARD_NO);
ALTER TABLE BOARD_JOB ADD CONSTRAINT BOARD_JOB_FK FOREIGN KEY(BOARD_WRITER) REFERENCES MEMBER(MEMBER_NICKNAME);
ALTER TABLE BOARD_JOB ADD CONSTRAINT BOARD_JOB_STATUS_CHK CHECK(BOARD_STATUS IN (0,1));

CREATE SEQUENCE BOARD_JOB_SEQ START WITH 1;
CREATE OR REPLACE TRIGGER BOARD_JOB_TRG
BEFORE INSERT ON BOARD_JOB
FOR EACH ROW
BEGIN
SELECT BOARD_JOB_SEQ.NEXTVAL
INTO :NEW.BOARD_NO
FROM DUAL;
END;
/
COMMIT;

CREATE TABLE APPLY_JOB(
  APPLY_BOARD_NO NUMBER(5) NOT NULL,
  APPLY_MEMBER_NO NUMBER(5) NOT NULL,
  APPLY_RESUME VARCHAR2(100) NOT NULL,
  APPLY_INTRO VARCHAR2(100) NOT NULL
);
ALTER TABLE APPLY_JOB ADD CONSTRAINT APPLY_BOARD_FK FOREIGN KEY(APPLY_BOARD_NO) REFERENCES BOARD_JOB(BOARD_NO);
ALTER TABLE APPLY_JOB ADD CONSTRAINT APPLY_MEMBER_FK FOREIGN KEY(APPLY_MEMBER_NO) REFERENCES MEMBER(MEMBER_NO);

CREATE TABLE FILE_BOARD_JOB(
 FILE_BOARD_NO NUMBER(3) NOT NULL,
 FILE_ORG_NAME VARCHAR2(300) NOT NULL,
 FILE_RE_NAME VARCHAR2(300) NOT NULL
)
ALTER TABLE FILE_BOARD_JOB ADD CONSTRAINT FILE_BOARD_JOB_FK FOREIGN KEY(FILE_BOARD_NO) REFERENCES BOARD_JOB(BOARD_NO);
CREATE TABLE HASHTAG_JOB(
 HASHTAG_BOARD_NO NUMBER(3) NOT NULL,
 HASHTAG_NO NUMBER(3) NOT NULL
);
ALTER TABLE HASHTAG_JOB ADD CONSTRAINT HASHTAG_JOB_BNO_FK FOREIGN KEY(HASHTAG_BOARD_NO) REFERENCES BOARD_JOB(BOARD_NO);
ALTER TABLE HASHTAG_JOB ADD CONSTRAINT HASHTAG_JOB_NO_FK FOREIGN KEY(HASHTAG_NO) REFERENCES HASHTAG(HASHTAG_NO);

